// <auto-generated />
using System;
using InfotecsTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfotecsTask.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260127131356_Modifyed_Added_Files2")]
    partial class Modifyed_Added_Files2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfotecsTask.Models.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("InfotecsTask.Models.Results", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<decimal>("AvgValue")
                        .HasColumnType("numeric");

                    b.Property<double>("DeltaTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedianValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("InfotecsTask.Models.Values", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("InfotecsTask.Models.Results", b =>
                {
                    b.HasOne("InfotecsTask.Models.Files", "File")
                        .WithOne("Result")
                        .HasForeignKey("InfotecsTask.Models.Results", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("InfotecsTask.Models.Values", b =>
                {
                    b.HasOne("InfotecsTask.Models.Files", "File")
                        .WithMany("Values")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("InfotecsTask.Models.Files", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
